[package]
name = "LearnRust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-beta.1"
reqwest = { version = "0.12.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.134"
